# Generated by Django 4.2.2 on 2023-06-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facerecognition',
            name='face_name',
            field=models.TextField(default='No Faces Detected.'),
        ),
    ]
