# Generated by Django 4.2.2 on 2023-06-21 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_facerecognition_face_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField()),
                ('employee_name', models.CharField()),
                ('mark_date', models.DateField(default=datetime.date(2023, 6, 21))),
                ('mark_time', models.TimeField(default=datetime.time(8, 38, 10, 777597))),
                ('shift', models.CharField(choices=[('Shift 1 Clock in', 'Shift 1 Clock in'), ('Shift 1 Clock out', 'Shift 1 Clock out'), ('Shift 2 Clock in', 'Shift 2 Clock in'), ('Shift 2 Clock out', 'Shift 2 Clock out')])),
            ],
        ),
    ]
