# Generated by Django 4.2.2 on 2023-06-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_markattendance_mark_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markattendance',
            name='shift',
            field=models.CharField(choices=[('Morning_In', 'Morning_In'), ('Morning_Out', 'Morning_Out'), ('Evening_In', 'Evening_In'), ('Evening_Out', 'Evening_Out')]),
        ),
    ]
