# Generated by Django 4.2.2 on 2023-06-21 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_markattendance_employee_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaceRecognition',
        ),
    ]
